url: /
baseurl:
permalink: /:categories/:title/
name: Miika Kangasniemi.net
menu:
    -
        text: Portfolio
        url: /#portfolio
    -
        text: Hinnat
        url: /#hinnat
    -
        text: Yhteystiedot
        url: /#yhteystiedot
exclude: [ 'sass', 'config.rb', 'Procfile', 'Thumbs.db' ]
prose:
    rooturl: _posts
    media: media
    metadata:
        _posts:
            - name: layout
              field:
                element: select
                label: Layout
                options:
                    - name: Default
                      value: default
                    - name: Miika
                      value: miika
                    - name: Category
                      value: category
            - name: permalink
              field:
                element: text
                label: URL
                value: 
            - name: show_title
              field:
                element: checkbox
                label: Näytä otsikko
        _posts/static:
            - name: layout
              field:
                element: select
                label: Layout
                options:
                    - name: Default
                      value: default
                    - name: Miika
                      value: miika
                    - name: Category
                      value: category
            - name: permalink
              field:
                element: text
                label: URL
                value: 
            - name: show_title
              field:
                element: checkbox
                label: Näytä otsikko
            - name: imagename
              field:
                element: text
                label: Iso kuva
                placeholder: theme-images/miika-iso.png
        _posts/yritysgrafiikka:
            - name: layout
              field:
                element: select
                label: Layout
                options:
                    - name: Default
                      value: default
                    - name: Miika
                      value: miika
                    - name: Category
                      value: category
            - name: show_title
              field:
                element: checkbox
                label: Näytä otsikko?
            - name: categories
              field:
                element: hidden
                value: [yritysgrafiikka]
            - name: "box-image"
              field:
                element: text
                label: Neliön kuva
                placeholder: yritysgrafiikka/kuvan-nimi.png
