url: /
baseurl:
permalink: /:categories/:title/
name: Miika Kangasniemi.net
menu:
    -
        text: Valokuvat
        url: /valokuvat
        imagename: valokuvat.jpg
    -
        text: Taulut
        url: /taulut
        imagename: taulut.jpg
    -
        text: Videot
        url: /videot
        imagename: videot.jpg
    -
        text: Taitot
        url: /taitot
        imagename: taitot.jpg
    -
        text: Yritysgrafiikka
        url: /yritysgrafiikka
        imagename: yritysgrafiikka.jpg
    -
        text: Julisteet
        url: /julisteet
        imagename: julisteet.jpg
    -
        text: WWW-sivut
        url: /www-sivut
        imagename: www-sivut.jpg
    -
        text: Miika Kangasniemi
        url: /miika-kangasniemi
        imagename: miika.jpg

exclude: [ 'sass', 'config.rb', 'Procfile', 'Thumbs.db' ]
prose:
    rooturl: _posts
    media: media
    metadata:
        _posts:
            - name: layout
              field:
                element: select
                options:
                    - name: Default
                      value: default
                    - name: Miika
                      value: miika
                    - name: Category
                      value: category
            - name: permalink
              field:
                element: text
                label: URL
                value: 
        _posts/yritysgrafiikka:
            - name: category
              field:
                type: hidden
                value: yritysgrafiikka
